[package]
edition = "2021"
name = "how"
version = "0.1.0"

[dependencies]
clap = {version = "4.5.23", features = ["derive"]}
futures = "0.3.31"
nom = "7.1.3"
tokio = {version = "1", features = ["full"]}
